### ISSUE TITLE
 PG::UnableToSend: unexpected response from server; first received character was "V" 

### ISSUE THREAD

**Issue by Artemiy17** [lsylvester/active_storage-postgresql#18]
I am trying to upload image through admin panel provided by `rails_admin` gem.
I got this error.

ActiveRecord::StatementInvalid in RailsAdmin::MainController#new
**PG::UnableToSend: unexpected response from server; first received character was "V"** 

My gems:
`ruby '3.2.0'`
`gem 'rails', '~> 7.0.4', '>= 7.0.4.1'`
`gem 'pg', '~> 1.1'`
`gem 'rails_admin', '~> 3.1', '>= 3.1.1'`
`gem "sassc-rails"`
`gem 'active_storage-postgresql', '~> 0.3.0'`

Started POST "/admin/document/new" for 127.0.0.1 at 2023-03-03 20:33:19 -0800
Processing by RailsAdmin::MainController#new as TURBO_STREAM
Parameters: {"authenticity_token"=>"[FILTERED]", "document"=>{"title"=>"123", "image"=>#<ActionDispatch::Http::UploadedFile:0x0000000109846f48 @tempfile=#<Tempfile:/var/folders/s0/k5xct5sx2sq659kn8r_k0x1h0000gn/T/RackMultipart20230303-6115-lq6z0c.png>, @original_filename="Screen Shot 2023-03-02 at 8.39.18 PM.png", @content_type="image/png", @headers="Content-Disposition: form-data; name=\"document[image]\"; filename=\"Screen Shot 2023-03-02 at 8.39.18 PM.png\"\r\nContent-Type: image/png\r\n">}, "return_to"=>"http://localhost:3000/admin/document/", "_save"=>"", "model_name"=>"document"}
User Load (0.7ms)  SELECT "users".* FROM "users" WHERE "users"."remember_token" = $1 ORDER BY "users"."id" ASC LIMIT $2  [["remember_token", "[FILTERED]"], ["LIMIT", 1]]
↳ config/initializers/rails_admin.rb:7:in `block (2 levels) in \<main>'
TRANSACTION (0.2ms)  BEGIN
Document Create (2.2ms)  INSERT INTO "documents" ("title", "created_at", "updated_at") VALUES ($1, $2, $3) RETURNING "id"  [["title", "123"], ["created_at", "2023-03-04 04:33:19.232307"], ["updated_at", "2023-03-04 04:33:19.232307"]]
ActiveStorage::Blob Load (0.6ms)  SELECT "active_storage_blobs".* FROM "active_storage_blobs" INNER JOIN "active_storage_attachments" ON "active_storage_blobs"."id" = "active_storage_attachments"."blob_id" WHERE "active_storage_attachments"."record_id" = $1 AND "active_storage_attachments"."record_type" = $2 AND "active_storage_attachments"."name" = $3 LIMIT $4  [["record_id", 3], ["record_type", "Document"], ["name", "image"], ["LIMIT", 1]]
ActiveStorage::Attachment Load (0.2ms)  SELECT "active_storage_attachments".* FROM "active_storage_attachments" WHERE "active_storage_attachments"."record_id" = $1 AND "active_storage_attachments"."record_type" = $2 AND "active_storage_attachments"."name" = $3 LIMIT $4  [["record_id", 3], ["record_type", "Document"], ["name", "image"], ["LIMIT", 1]]
ActiveStorage::Blob Create (0.6ms)  INSERT INTO "active_storage_blobs" ("key", "filename", "content_type", "metadata", "service_name", "byte_size", "checksum", "created_at") VALUES ($1, $2, $3, $4, $5, $6, $7, $8) RETURNING "id"  [["key", "qv3drvtayn7nyl2zzty31wrbyydd"], ["filename", "Screen Shot 2023-03-02 at 8.39.18 PM.png"], ["content_type", "image/png"], ["metadata", "{\"identified\":true}"], ["service_name", "local"], ["byte_size", 194395], ["checksum", "faS7VZpiXhQrlKCXzCgEUw=="], ["created_at", "2023-03-04 04:33:19.248084"]]
ActiveStorage::Attachment Create (0.8ms)  INSERT INTO "active_storage_attachments" ("name", "record_type", "record_id", "blob_id", "created_at") VALUES ($1, $2, $3, $4, $5) RETURNING "id"  [["name", "image"], ["record_type", "Document"], ["record_id", 3], ["blob_id", 3], ["created_at", "2023-03-04 04:33:19.252019"]]
Document Update (3.1ms)  UPDATE "documents" SET "updated_at" = $1 WHERE "documents"."id" = $2  [["updated_at", "2023-03-04 04:33:19.255100"], ["id", 3]]
TRANSACTION (1.4ms)  COMMIT
TRANSACTION (0.1ms)  BEGIN
TRANSACTION (1.8ms)  ROLLBACK
message type 0x43 arrived from server while idle
message type 0x5a arrived from server while idle
PostgreSQL Storage (7.9ms) Uploaded file to key: qv3drvtayn7nyl2zzty31wrbyydd (checksum: faS7VZpiXhQrlKCXzCgEUw==)
Completed 500 Internal Server Error in 47ms (ActiveRecord: 12.0ms | Allocations: 22980)

ActiveRecord::StatementInvalid (PG::UnableToSend: unexpected response from server; first received character was "V"):

**Comment by Nerian** [comment]
Should be fixed by https://github.com/lsylvester/active_storage-postgresql/pull/17 once @lsylvester  merges it.

**Comment by lsylvester** [comment]
#17 has been merged and released so this should be resolved.
